# -*- coding: utf-8 -*-
"""Bankrask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYY11KPcCfgbxMwSnGzI9yFiBBlSHS-5
"""

class Account:
    def __init__(self, account_number, customer_name, balance):
        self.account_number = account_number
        self.customer_name = customer_name
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print("Amount deposited:", amount)

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            print("Amount withdrawn:", amount)
        else:
            print("Insufficient balance")

    def calculate_profit(self):
        return 0


class SavingsAccount(Account):
    def calculate_profit(self):
        return self.balance * 0.10


class CurrentAccount(Account):
    def calculate_profit(self):
        return 0


class BusinessAccount(Account):
    def calculate_profit(self):
        return self.balance * 0.05


# Objects
savings = SavingsAccount("PK001", "Ali", 50000)
current = CurrentAccount("PK002", "Ahmed", 70000)
business = BusinessAccount("PK003", "Usman", 100000)

# Savings Account
savings.deposit(5000)
savings.withdraw(10000)
print("Savings Profit:", savings.calculate_profit())
print("Savings Balance:", savings.balance)

# Current Account
current.deposit(10000)
current.withdraw(5000)
print("Current Profit:", current.calculate_profit())
print("Current Balance:", current.balance)

# Business Account
business.deposit(20000)
business.withdraw(15000)
print("Business Profit:", business.calculate_profit())
print("Business Balance:", business.balance)