# -*- coding: utf-8 -*-
"""vehicle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-ab1NHkmloj_xYd5MzdbOEPEAUOT825
"""

class Vehicle:
  def __init__(self, registration_no, model, fuel_type):
    self.registration_no = registration_no
    self.model = model
    self.fuel_type = fuel_type

  def show_details(self):
    print("Registration_no:" , self.registration_no)
    print("Model:" , self.model)
    print("Fuel_type:" , self.fuel_type)


class Car(Vehicle):
  def open_trunk(self):
    print("Car trunk is opened")

class Bus(Vehicle):
  def passanger_capacity(self):
    print("Bus can carry many passangers")

class Truck(Vehicle):
  def load_goods(self):
    print("truck is loading goods")




print("Car:")
c1 = Car("LEA-123", "Toyota Corolla", "Petrol")
c1.show_details()
c1.open_trunk()
print("---------------------------")


print("Bus:")
b1 = Bus("LHR-123", "Daewoo bus", "Diesel")
b1.show_details()
b1.passanger_capacity()
print("---------------------------")


print("Truck:")
t1 = Truck("ISB-786", "Hino", "Diesel")
t1.show_details()
t1.load_goods()
print("---------------------------")